[2020-11-03 21:46:03,450][MainThread:21336][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2020-11-03 21:47:08,109][MainThread:12644][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2020-11-03 21:47:30,634][ThreadPoolExecutor-1_0:17036][task_id:django.request][log.py:228][WARNING][Not Found: /]
[2020-11-03 21:47:30,637][django-main-thread:12752][task_id:django.channels.server][runserver.py:149][WARNING][HTTP GET / 404 [0.02, 127.0.0.1:28770]]
[2020-11-03 21:47:30,780][ThreadPoolExecutor-1_0:17036][task_id:django.request][log.py:228][WARNING][Not Found: /favicon.ico]
[2020-11-03 21:47:30,783][django-main-thread:12752][task_id:django.channels.server][runserver.py:149][WARNING][HTTP GET /favicon.ico 404 [0.01, 127.0.0.1:28770]]
[2020-11-03 21:47:40,956][ThreadPoolExecutor-1_1:15428][task_id:django.request][log.py:228][ERROR][Internal Server Error: /a]
Traceback (most recent call last):
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\views.py", line 507, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\views.py", line 422, in finalize_response
    % type(response)
AssertionError: Expected a `Response`, `HttpResponse` or `HttpStreamingResponse` to be returned from the view, but received a `<class 'NoneType'>`
[2020-11-03 21:47:40,996][django-main-thread:12752][task_id:django.channels.server][runserver.py:154][ERROR][HTTP GET /a 500 [0.04, 127.0.0.1:28770]]
[2020-11-03 21:57:48,984][MainThread:18728][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2020-11-03 22:07:24,698][MainThread:18728][task_id:django.utils.autoreload][autoreload.py:217][INFO][C:\Users\m\PycharmProjects\HotSchool\apps\user\models.py changed, reloading.]
[2020-11-03 22:07:26,387][MainThread:11772][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2020-11-04 09:25:30,346][MainThread:14604][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2020-11-04 09:27:01,374][ThreadPoolExecutor-1_0:22120][task_id:django.request][log.py:228][ERROR][Internal Server Error: /login]
Traceback (most recent call last):
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
[2020-11-04 09:27:01,412][django-main-thread:19392][task_id:django.channels.server][runserver.py:154][ERROR][HTTP POST /login 500 [0.81, 10.129.9.2:59416]]
[2020-11-04 09:27:28,911][django-main-thread:19392][task_id:django.channels.server][runserver.py:141][INFO][HTTP GET /recommend?school=-1&type=0 200 [0.05, 10.129.9.2:59416]]
[2020-11-04 09:27:41,235][MainThread:20968][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2020-11-04 09:27:58,170][ThreadPoolExecutor-1_0:21584][task_id:django.request][log.py:228][ERROR][Internal Server Error: /login]
Traceback (most recent call last):
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
[2020-11-04 09:27:58,173][django-main-thread:18456][task_id:django.channels.server][runserver.py:154][ERROR][HTTP POST /login 500 [2.77, 10.129.9.2:59444]]
[2020-11-04 09:29:28,509][MainThread:9172][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2020-11-04 09:29:36,600][ThreadPoolExecutor-1_0:18496][task_id:django.request][log.py:228][ERROR][Internal Server Error: /login]
Traceback (most recent call last):
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "C:\Users\m\Envs\hotschool\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\renderers.py", line 104, in render
    allow_nan=not self.strict, separators=separators
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\m\Envs\hotschool\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "c:\users\m\appdata\local\programs\python\python37\Lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Response is not JSON serializable
[2020-11-04 09:29:36,605][django-main-thread:21964][task_id:django.channels.server][runserver.py:154][ERROR][HTTP POST /login 500 [0.47, 10.129.9.2:59514]]
[2020-11-04 09:31:27,200][MainThread:4724][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2020-11-04 09:31:37,967][django-main-thread:14248][task_id:django.channels.server][runserver.py:141][INFO][HTTP POST /login 200 [0.37, 10.129.9.2:59572]]
[2020-11-04 10:30:45,830][MainThread:2092][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2020-11-04 10:33:06,583][django-main-thread:21184][task_id:django.channels.server][runserver.py:141][INFO][HTTP GET /recommend?school=-1&type=0 200 [0.08, 10.129.9.2:62803]]
[2020-11-04 10:33:59,384][django-main-thread:21184][task_id:django.channels.server][runserver.py:141][INFO][HTTP GET /recommend?school=-1&type=0 200 [0.03, 10.129.9.2:62803]]
[2020-11-04 10:33:59,896][django-main-thread:21184][task_id:django.channels.server][runserver.py:162][INFO][WebSocket HANDSHAKING /ws/chat [10.129.9.2:62867]]
[2020-11-04 10:33:59,961][django-main-thread:21184][task_id:django.channels.server][runserver.py:158][INFO][WebSocket CONNECT /ws/chat [10.129.9.2:62867]]
[2020-11-04 10:33:59,990][django-main-thread:21184][task_id:django.channels.server][runserver.py:160][INFO][WebSocket DISCONNECT /ws/chat [10.129.9.2:62867]]
[2020-11-04 10:34:23,269][MainThread:19076][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2020-11-04 16:35:23,014][MainThread:2188][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2020-11-04 16:35:51,571][MainThread:3156][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
[2020-11-04 16:36:01,066][django-main-thread:15240][task_id:django.channels.server][runserver.py:141][INFO][HTTP GET /question/hot 200 [0.07, 10.129.9.2:53691]]
[2020-11-04 16:36:02,213][django-main-thread:15240][task_id:django.channels.server][runserver.py:162][INFO][WebSocket HANDSHAKING /ws/chat [10.129.9.2:53695]]
[2020-11-04 16:36:02,265][django-main-thread:15240][task_id:django.channels.server][runserver.py:158][INFO][WebSocket CONNECT /ws/chat [10.129.9.2:53695]]
[2020-11-04 16:36:04,075][django-main-thread:15240][task_id:django.channels.server][runserver.py:141][INFO][HTTP PUT /user/userinfo 200 [0.02, 10.129.9.2:53706]]
[2020-11-04 16:36:04,076][django-main-thread:15240][task_id:django.channels.server][runserver.py:141][INFO][HTTP GET /user/infoshow/19 200 [0.04, 10.129.9.2:53691]]
[2020-11-04 16:36:04,080][django-main-thread:15240][task_id:django.channels.server][runserver.py:141][INFO][HTTP GET /upload 200 [0.03, 10.129.9.2:53705]]
[2020-11-04 16:36:04,137][django-main-thread:15240][task_id:django.channels.server][runserver.py:141][INFO][HTTP GET /user/dynamic/19 200 [0.09, 10.129.9.2:53704]]
[2020-11-04 16:36:11,442][django-main-thread:15240][task_id:django.channels.server][runserver.py:141][INFO][HTTP PUT /user/userinfo 200 [0.01, 10.129.9.2:53704]]
[2020-11-04 16:36:11,894][django-main-thread:15240][task_id:django.channels.server][runserver.py:141][INFO][HTTP PUT /user/userinfo 200 [0.22, 10.129.9.2:53704]]
[2020-11-04 16:36:18,703][django-main-thread:15240][task_id:django.channels.server][runserver.py:160][INFO][WebSocket DISCONNECT /ws/chat [10.129.9.2:53695]]
[2020-11-04 16:36:20,191][django-main-thread:15240][task_id:django.channels.server][runserver.py:141][INFO][HTTP GET /question/hot 200 [0.02, 10.129.9.2:53704]]
[2020-11-04 16:36:21,025][django-main-thread:15240][task_id:django.channels.server][runserver.py:162][INFO][WebSocket HANDSHAKING /ws/chat [10.129.9.2:53777]]
[2020-11-04 16:36:21,025][django-main-thread:15240][task_id:django.channels.server][runserver.py:164][INFO][WebSocket REJECT /ws/chat [10.129.9.2:53777]]
[2020-11-04 16:36:21,026][django-main-thread:15240][task_id:django.channels.server][runserver.py:160][INFO][WebSocket DISCONNECT /ws/chat [10.129.9.2:53777]]
[2020-11-04 16:36:51,047][django-main-thread:15240][task_id:django.channels.server][runserver.py:162][INFO][WebSocket HANDSHAKING /ws/chat [10.129.9.2:53871]]
[2020-11-04 16:36:51,048][django-main-thread:15240][task_id:django.channels.server][runserver.py:164][INFO][WebSocket REJECT /ws/chat [10.129.9.2:53871]]
[2020-11-04 16:36:51,048][django-main-thread:15240][task_id:django.channels.server][runserver.py:160][INFO][WebSocket DISCONNECT /ws/chat [10.129.9.2:53871]]
[2020-11-05 13:03:44,375][MainThread:5008][task_id:django.utils.autoreload][autoreload.py:597][INFO][Watching for file changes with StatReloader]
